name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 7 * * 2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu2404
          - debian12
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          image: ${{ matrix.image }}
